import type { Metadata } from "next";
import "./globals.css";
import FloatingImage from "@/components/preloadpg";
import Navbar from "@/components/navbar";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // Adjust as needed
  variable: "--font-montserrat", // Optional CSS variable
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar/>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <FloatingImage/>
        {children}
      </body>
    </html>
  );
}
